'use client';

import React from 'react';
import { Card, CardHeader, CardTitle, CardContent } from '@/components/ui';
import { CashBookEntry } from '@/types/finance';
import { cn } from '@/lib/utils';

interface CashBookTableProps {
    data: CashBookEntry[];
    totalIn: number;
    totalOut: number;
    cashInHand: number;
}

const CashBookTable: React.FC<CashBookTableProps> = ({ data, totalIn, totalOut, cashInHand }) => {
    return (
        <Card className="overflow-hidden border-surface-border dark:border-dark-border">
            <CardHeader className="bg-surface-page dark:bg-dark-page/50 border-b border-surface-border dark:border-dark-border">
                <CardTitle className="text-xl font-bold text-center">CashBook</CardTitle>
            </CardHeader>
            <CardContent className="p-0">
                <div className="overflow-x-auto">
                    <table className="w-full text-left border-collapse">
                        <thead>
                            <tr className="bg-surface-page/50 dark:bg-white/5 border-b border-surface-border dark:border-dark-border">
                                <th className="px-6 py-4 text-xs font-bold text-ink-muted uppercase border-r border-surface-border dark:border-dark-border">Cash In Type</th>
                                <th className="px-6 py-4 text-xs font-bold text-ink-muted uppercase border-r border-surface-border dark:border-dark-border">Amount</th>
                                <th className="px-6 py-4 text-xs font-bold text-ink-muted uppercase border-r border-surface-border dark:border-dark-border">Cash Out Type</th>
                                <th className="px-6 py-4 text-xs font-bold text-ink-muted uppercase">Amount</th>
                            </tr>
                        </thead>
                        <tbody className="divide-y divide-surface-border dark:divide-dark-border">
                            {data.map((entry) => (
                                <tr key={entry.id} className="hover:bg-surface-hover/30 dark:hover:bg-white/5 transition-colors">
                                    <td className="px-6 py-4 text-sm font-medium text-ink-body dark:text-gray-300 border-r border-surface-border dark:border-dark-border">{entry.cashInType}</td>
                                    <td className="px-6 py-4 text-sm font-bold text-success border-r border-surface-border dark:border-dark-border">
                                        {entry.cashInAmount > 0 ? `Tk ${entry.cashInAmount.toLocaleString()}` : 'Tk 0'}
                                    </td>
                                    <td className="px-6 py-4 text-sm font-medium text-ink-body dark:text-gray-300 border-r border-surface-border dark:border-dark-border">{entry.cashOutType}</td>
                                    <td className="px-6 py-4 text-sm font-bold text-danger">
                                        {entry.cashOutAmount > 0 ? `Tk ${entry.cashOutAmount.toLocaleString()}` : 'Tk 0'}
                                    </td>
                                </tr>
                            ))}
                        </tbody>
                        <tfoot>
                            <tr className="bg-surface-page/80 dark:bg-white/5 font-bold border-t-2 border-surface-border dark:border-dark-border">
                                <td className="px-6 py-4 text-sm text-ink-heading dark:text-white border-r border-surface-border dark:border-dark-border">Total In</td>
                                <td className="px-6 py-4 text-sm text-success border-r border-surface-border dark:border-dark-border font-black">Tk {totalIn.toLocaleString()}</td>
                                <td className="px-6 py-4 text-sm text-ink-heading dark:text-white border-r border-surface-border dark:border-dark-border">Total Out</td>
                                <td className="px-6 py-4 text-sm text-danger font-black">Tk {totalOut.toLocaleString()}</td>
                            </tr>
                            <tr className="bg-brand/10 dark:bg-brand/20 font-black">
                                <td colSpan={2} className="px-6 py-4 border-r border-surface-border dark:border-dark-border italic text-ink-muted text-xs">
                                    Generated by Birdseye System
                                </td>
                                <td className="px-6 py-4 text-sm text-brand border-r border-surface-border dark:border-dark-border">Cash in Hand</td>
                                <td className="px-6 py-4 text-lg text-brand">Tk {cashInHand.toLocaleString()}</td>
                            </tr>
                        </tfoot>
                    </table>
                </div>
            </CardContent>
        </Card>
    );
};

export default CashBookTable;
